dataset_path : './data/dataset/shapenet_co3d'
sem_file: 'w2v' 

lr : 1e-4 
wd : 1e-6

epochs: 40
nclasses : 89
seed : 42

ntasks : 11 # number of tasks # 10
batch_size : 32
workers : 8
use_memory : false
num_samples : 1 # number of samples - 20

feature_dim : 1024
fewshot: 5
sim: 'cosine'


# cluster, without_knn, conc  for train_pointnet_task0_with_w2v.py, train_pointnet_task0_without_w2v.py; select 'cluster' or 'without_knn'
# cluster, conc for train_pointnet_incremental_with_knn_without_w2v.py, train_pointnet_incremental_with_knn_with_w2v.py; select 'cluster'
experiment: 'cluster'


ckpt: '/home/tudooh/qty/CLIP2PointCIL/CLIP2Point-main/pre_builts/vit32/best_eval.pth'
views: 6

cluster_num: 512
use_new_feats_p: false
feats_p_path: './lda/lda.pth'